name:                snail
version:             0.1.0.0
github:              "githubuser/snale"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/snale#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - unix
  - text
  - unordered-containers

executables:
  snail-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -feager-blackholing
    - -rtsopts
    - -with-rtsopts=-N
    - -XStrictData
    - -XStrict
    - -O3
#    - -dynamic
    dependencies:
    - snail
    - safe-exceptions
    - temporary
    - unordered-containers
    - scientific
    - process
    - directory
    - haskeline
    - bytestring
    - unix
    - filepath
    - mtl
    - text
    - megaparsec
    - debug
    - regex-posix
    - split
    - Glob
    - transformers
    - text-show

tests:
  snail-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snail
